TravelOrders/Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelOrders.bl;
using TravelOrders.Models;

namespace TravelOrders.Controllers
{
    public class DriverController : MyController
    {
        // GET: Driver
        public ActionResult Index()
        {
            return View(manager.GetDrivers());
        }

        [HttpGet]
        public ActionResult AddDriver()
        {
            return View(new Driver());
        }

        [HttpPost]
        public ActionResult AddDriver(Driver model) 
        {
            //Driver d = new Driver();
            //d.Name = model.Name;
            //d.Surname = model.Surname;
            //d.Mobile = model.Mobile;
            //d.LicenceNo = model.LicenceNo;

            manager.AddDriver(model);

            return RedirectToAction("Index");
        }

        public ActionResult DeleteDriver(Driver driver) {
            manager.DeleteDriver(driver.IDDriver);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditDriver(int idDriver)
        {
                        
            return View(manager.GetDriver(idDriver));
        }

        [HttpPost]
        public ActionResult EditDriver(Driver driver)
        {
            manager.EditDriver(driver);
            return RedirectToAction("Index");
        }

        //[HttpPost]
        //public ActionResult AddDriver(Driver model)
        //{
        //    //Driver d = new Driver();
        //    //d.Name = model.Name;
        //    //d.Surname = model.Surname;
        //    //d.Mobile = model.Mobile;
        //    //d.LicenceNo = model.LicenceNo;

        //    manager.AddDriver(model);

        //    return RedirectToAction("Index");
        //}
    }
}

TravelOrders/Controllers/XmlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelOrders.dal;

namespace TravelOrders.Controllers
{
    public class XmlController : Controller
    {
        private XmlHandler xml = new XmlHandler();
        SqlRepository sql = new SqlRepository();
        // GET: Xml
        public ActionResult Backup()
        {
            xml.CreateXml();
            return View();
        }

        public ActionResult Restore()
        {
            xml.ReadXml();
            return Content(xml.getTest());
        }

        public ActionResult RouteToXml(int idRoute)
        {
            sql.WriteRouteToXml(idRoute);
            return RedirectToAction("GetRoutes", "Route",new { idTravelOrder = sql.GetRoutes().Where(r=> r.IDRoute==idRoute).First().TravelOrder.IDTravelOrder });
        }

        public ActionResult ReadRoute()
        {
            sql.ReadRouteFromXml();
            return RedirectToAction("GetTravelOrders","TravelOrder");
        }
    }
}

TravelOrders/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Trael Orders</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Travel Orders", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Drivers", "Index", "Driver")</li>
                    <li>@Html.ActionLink("Vehicles", "ViewVehicles", "Vehicle")</li>
                    <li>@Html.ActionLink("Travel Orders", "GetTravelOrders", "TravelOrder")</li>
                    <li>@Html.ActionLink("Add Service", "Create", "Services")</li>
                    <li>@Html.ActionLink("Backup", "Backup", "Xml")</li>
                    <li>@Html.ActionLink("Restore", "Restore", "Xml")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Travel Orders</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>