TravelOrders/Models/TravelOrder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TravelOrders.Models
{
    public class TravelOrder
    {
        public int IDTravelOrder { get; set; }
        [Required]
        public string TravelOrderNo { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime TravelOrderDate { get; set; }
        public Driver Driver { get; set; }
        public Vehicle Vehicle { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime DateOfDeparture { get; set; }
        [DataType(DataType.Time)]
        [Required]
        public DateTime StartTime { get; set; }
        [Required]
        [DataType(DataType.Time)]
        public DateTime EndTime { get; set; }
        [Required]
        public string DestinationStart { get; set; }
        [Required]
        public string DestinationEnd { get; set; }
        [Required]
        [Range(0, 200000)]
        public double BeginningCounterStatus { get; set; }
        [Required]
        [Range(10, 200500)]
        public double EndCounterStatus { get; set; }
        public TravelOrderType TravelOrderType { get; set; }
        public DailyAllowance DailyAllowance { get; set; }

        public TravelOrder(int id)
        {
            this.IDTravelOrder = id;
        }


        public TravelOrder()
        {

        }

        public TravelOrder(int idTravelOrder, string travelOrderNo, DateTime travelOrderDate, Driver driver, Vehicle vehicle, DateTime dateOfDeparture, string destinationStart, string destinationEnd, double beginningCounterStatus, double endCounterStatus, TravelOrderType travelOrderType, DailyAllowance dailyAllowance)
        {
            IDTravelOrder = idTravelOrder;
            TravelOrderNo = travelOrderNo;
            TravelOrderDate = travelOrderDate;
            Driver = driver;
            Vehicle = vehicle;
            DateOfDeparture = dateOfDeparture;
            DestinationStart = destinationStart;
            DestinationEnd = destinationEnd;
            BeginningCounterStatus = beginningCounterStatus;
            EndCounterStatus = endCounterStatus;
            TravelOrderType = travelOrderType;
            DailyAllowance = dailyAllowance;
        }


        public override string ToString()
        {
            return $"{TravelOrderNo}";
        }
    }
}

TravelOrders/Models/TravelOrderType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TravelOrders.Models
{
    public class TravelOrderType
    {
        public int IDTravelOrderType { get; set; }
        public string Type { get; set; }

        public TravelOrderType()
        {

        }

        public TravelOrderType(int idTravelOrderType, string type)
        {
            IDTravelOrderType = idTravelOrderType;
            Type = type;
        }

        public override string ToString()
        {
            return $"{Type}";
        }
    }
}

TravelOrders/Controllers/RouteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelOrders.bl;
using TravelOrders.Models;

namespace TravelOrders.Controllers
{
    public class RouteController : MyController
    {
        // GET: Route
        public ActionResult GetRoutes(int idTravelOrder)
        {
            return View(manager.GetRoutes().Where(r=> r.TravelOrder.IDTravelOrder==idTravelOrder));
        }

            // GET: Route/Details/5
        public ActionResult Details(int idRoute)
        {
            return View();
        }

        // GET: Route/Create
        public ActionResult AddRoute()
        {
           
            ViewBag.travelOrder = new SelectList(manager.GetTravelOrders(), "IDTravelOrder", "TravelOrderNo");
            return View();
        }

      

        // POST: Route/Create
        [HttpPost]
        public ActionResult AddRoute(Route route)
        {
            try
            {
                int id = route.TravelOrder.IDTravelOrder;
                manager.AddRoute(route);
                return RedirectToAction("GetRoutes", new { idTravelOrder = route.TravelOrder.IDTravelOrder });
            }
            catch
            {
                return View();
            }
          

        }

        // GET: Route/Edit/5
        public ActionResult EditRoute(int idRoute)
        {
            ViewBag.travelOrder = new SelectList(manager.GetTravelOrders(), "IDTravelOrder", "TravelOrderNo");
            return View(manager.GetRoutes().Where(r=> r.IDRoute==idRoute).First());
        }

        // POST: Route/Edit/5
        [HttpPost]
        public ActionResult EditRoute(Route route)
        {
            try
            {
                manager.EditRoute(route);
                return RedirectToAction("GetRoutes", new { idTravelOrder = route.TravelOrder.IDTravelOrder });
            }
            catch
            {
                return View();
            }
            
        }

        // GET: Route/Delete/5
        public ActionResult DeleteRoute(int idRoute)
        {
            manager.DeleteRoute(idRoute);
            return RedirectToAction("GetTravelOrders","TravelOrder");
        }

      
    }
}

TravelOrders/Controllers/TravelOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelOrders.bl;
using TravelOrders.Models;

namespace TravelOrders.Controllers
{
    public class TravelOrderController : MyController
    {
        
        public ActionResult GetTravelOrders()
        {
            ViewBag.filter = manager.GetTravelOrderTypes();
            return View(manager.GetTravelOrders());
        }

        // GET: Route/Details/5
        public ActionResult Routes(int id)
        {
            return View(manager.GetRoutesForTravelOrder(id));
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult AddTravelOrder()
        {
            ViewBag.drivers =  new SelectList(manager.GetDrivers(), "IDDriver", "Surname");
            ViewBag.vehicles = new SelectList(manager.GetVehicles(), "IDVehicle", "Type");
            ViewBag.toType = new SelectList(manager.GetTravelOrderTypes(), "IDTravelOrderType", "Type");
            ViewBag.allowance = new SelectList(manager.GetDailyAllowances(), "IDDailyAllowance", "DaysHoursValue");
            ViewBag.brands = new SelectList(manager.GetBrands(), "IDBrand", "Name");
            return View();
        }

       
        [HttpPost]
        public ActionResult AddTravelOrder(TravelOrder travelOrder)
        {
           
            manager.AddTravelOrder(travelOrder);
            return RedirectToAction("GetTravelOrders");
        }

        
        public ActionResult EditTravelOrder(int idTravelOrder)
        {
            ViewBag.drivers = manager.GetDrivers();
            ViewBag.vehicles = manager.GetVehicles();
            ViewBag.toType = manager.GetTravelOrderTypes();
            ViewBag.allowance = manager.GetDailyAllowances();
            //ViewBag.travelOrderType = manager.GetVehicles();
            //ViewBag.dailyAllowance = manager.GetVehicles();

            return View(manager.GetTravelOrder(idTravelOrder));

            
        }

      
        [HttpPost]
        public ActionResult EditTravelOrder(TravelOrder travelOrder)
        {
           
            manager.EditTravelOrder(travelOrder);
            return RedirectToAction("GetTravelOrders");
        }

        
        public ActionResult DeleteTravelOrder(int idTravelOrder)
        {
            manager.DeleteTravelOrder(idTravelOrder);
            return RedirectToAction("GetTravelOrders");
        }


        public ActionResult FilterFuture()
        {
         
            return View(manager.FilterTravelOrders(3));
        }

        public ActionResult FilterOpened()
        {

            return View(manager.FilterTravelOrders(2));
        }

        public ActionResult FilterClosed()
        {

            return View(manager.FilterTravelOrders(1));
        }

    }
}

TravelOrders/Views/TravelOrder/AddTravelOrder.cshtml
@model TravelOrders.Models.TravelOrder

@{
    ViewBag.Title = "AddTravelOrder";
}

<h2>AddTravelOrder</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>TravelOrder</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">

        <div class="col-md-10">
            @Html.HiddenFor(model => model.IDTravelOrder, new { htmlAttributes = new { @class = "form-control" } })

        </div>
    </div>

    <div class="form-group">

        @Html.LabelFor(model => model.Driver.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Driver.IDDriver, (SelectList)@ViewBag.drivers, new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group">

        @Html.LabelFor(model => model.Vehicle.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Vehicle.IDVehicle, (SelectList)@ViewBag.vehicles, new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group">

        @Html.LabelFor(model => model.TravelOrderType.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.TravelOrderType.IDTravelOrderType, (SelectList)@ViewBag.toType, new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group">

        @Html.LabelFor(model => model.DailyAllowance.DaysHoursValue, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.DailyAllowance.IDDailyAllowance, (SelectList)@ViewBag.allowance, new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TravelOrderNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TravelOrderNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TravelOrderNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TravelOrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TravelOrderDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TravelOrderDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateOfDeparture, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateOfDeparture, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateOfDeparture, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DestinationStart, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DestinationStart, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DestinationStart, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DestinationEnd, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DestinationEnd, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DestinationEnd, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BeginningCounterStatus, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BeginningCounterStatus, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BeginningCounterStatus, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndCounterStatus, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndCounterStatus, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndCounterStatus, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

    <div>
        @Html.ActionLink("Back to List", "GetTravelOrders")
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TravelOrders/Views/TravelOrder/Details.cshtml
@model TravelOrders.Models.TravelOrder

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TravelOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDTravelOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDTravelOrder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TravelOrderNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TravelOrderNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TravelOrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TravelOrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfDeparture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfDeparture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DestinationStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DestinationStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DestinationEnd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DestinationEnd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BeginningCounterStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BeginningCounterStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndCounterStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndCounterStatus)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "GetTravelOrders")
</p>

TravelOrders/Views/TravelOrder/FilterClosed.cshtml
@model IEnumerable<TravelOrders.Models.TravelOrder>

@{
    ViewBag.Title = "FilterClosed";
}

<h2>FilterClosed</h2>

<p>

    @Html.ActionLink("Add Travel Order", "AddTravelOrder", "TravelOrder", new { @class = "btn btn-default" })
    @Html.ActionLink("Active travel orders", "FilterOpened", "TravelOrder", new { @class = "btn btn-default" })
    @Html.ActionLink("Closed travel Order", "FilterFuture", "TravelOrder", new { @class = "btn btn-default" })
    @Html.ActionLink("Future Travel Orders", "FilterClosed", "TravelOrder", new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IDTravelOrder)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TravelOrderNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TravelOrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfDeparture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DestinationStart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DestinationEnd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BeginningCounterStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndCounterStatus)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IDTravelOrder)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TravelOrderNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TravelOrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfDeparture)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DestinationStart)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DestinationEnd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BeginningCounterStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndCounterStatus)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditTravelOrder", new { @idTravelOrder = item.IDTravelOrder }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Routes", "GetRoutes", "Route", new { @idTravelOrder = item.IDTravelOrder }, new { @class = "btn btn-info" })
            @Html.ActionLink("Delete", "DeleteTravelOrder", new { @idTravelOrder = item.IDTravelOrder }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

TravelOrders/Views/TravelOrder/FilterFuture.cshtml
@model IEnumerable<TravelOrders.Models.TravelOrder>

@{
    ViewBag.Title = "FilterFuture";
}

<h2>FilterFuture</h2>

<p>

    @Html.ActionLink("Add Travel Order", "AddTravelOrder", "TravelOrder", new { @class = "btn btn-default" })
    @Html.ActionLink("Active travel orders", "FilterOpened", "TravelOrder", new { @class = "btn btn-default" })
    @Html.ActionLink("Closed travel Order", "FilterFuture", "TravelOrder", new { @class = "btn btn-default" })
    @Html.ActionLink("Future Travel Orders", "FilterClosed", "TravelOrder", new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IDTravelOrder)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TravelOrderNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TravelOrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfDeparture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DestinationStart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DestinationEnd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BeginningCounterStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndCounterStatus)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IDTravelOrder)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TravelOrderNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TravelOrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfDeparture)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DestinationStart)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DestinationEnd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BeginningCounterStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndCounterStatus)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditTravelOrder", new { @idTravelOrder = item.IDTravelOrder }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Routes", "GetRoutes", "Route", new { @idTravelOrder = item.IDTravelOrder }, new { @class = "btn btn-info" })
            @Html.ActionLink("Delete", "DeleteTravelOrder", new { @idTravelOrder = item.IDTravelOrder }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

TravelOrders/Views/TravelOrder/FilterOpened.cshtml
@model IEnumerable<TravelOrders.Models.TravelOrder>

@{
    ViewBag.Title = "FilterOpened";
}

<h2>FilterOpened</h2>

<p>

    @Html.ActionLink("Add Travel Order", "AddTravelOrder", "TravelOrder", new { @class = "btn btn-default" })
    @Html.ActionLink("Active travel orders", "FilterOpened", "TravelOrder", new { @class = "btn btn-default" })
    @Html.ActionLink("Closed travel Order", "FilterFuture", "TravelOrder", new { @class = "btn btn-default" })
    @Html.ActionLink("Future Travel Orders", "FilterClosed", "TravelOrder", new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IDTravelOrder)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TravelOrderNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TravelOrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfDeparture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DestinationStart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DestinationEnd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BeginningCounterStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndCounterStatus)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IDTravelOrder)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TravelOrderNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TravelOrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfDeparture)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DestinationStart)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DestinationEnd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BeginningCounterStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndCounterStatus)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditTravelOrder", new { @idTravelOrder = item.IDTravelOrder }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Routes", "GetRoutes", "Route", new { @idTravelOrder = item.IDTravelOrder }, new { @class = "btn btn-info" })
            @Html.ActionLink("Delete", "DeleteTravelOrder", new { @idTravelOrder = item.IDTravelOrder }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

TravelOrders/Views/TravelOrder/GetTravelOrders.cshtml
@model IEnumerable<TravelOrders.Models.TravelOrder>

@{
    ViewBag.Title = "GetTravelOrders";
}

<h2>GetTravelOrders</h2>

<p>

    @Html.ActionLink("Add Travel Order", "AddTravelOrder", "TravelOrder", new { @class = "btn btn-default" })
    @Html.ActionLink("Active travel orders", "FilterOpened", "TravelOrder", new { @class = "btn btn-default" })
    @Html.ActionLink("Closed travel Order", "FilterFuture", "TravelOrder", new { @class = "btn btn-default" })
    @Html.ActionLink("Future Travel Orders", "FilterClosed", "TravelOrder", new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.TravelOrderNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TravelOrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfDeparture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DestinationStart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DestinationEnd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BeginningCounterStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndCounterStatus)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        @Html.HiddenFor(modelItem => item.IDTravelOrder)
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TravelOrderNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TravelOrderDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfDeparture)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DestinationStart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DestinationEnd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BeginningCounterStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndCounterStatus)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditTravelOrder", new { @idTravelOrder = item.IDTravelOrder }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Routes", "GetRoutes", "Route", new { @idTravelOrder = item.IDTravelOrder }, new { @class = "btn btn-info" })
                @Html.ActionLink("Delete", "DeleteTravelOrder", new { @idTravelOrder = item.IDTravelOrder }, new { @class = "btn btn-danger" })

            </td>
        </tr>
    }

</table>